kaltura/playkit-js-related

- src/related-manager.ts
If autoContinue is false, return countdownTime -1 which will prevent countdown from showing
Fixes FEC-11883
> fix(FEC-11883): Related: System shows the timer when the autoContinue = false

- src/components/related-overlay/related-overlay.tsx
When showOnPlaybackPaused is true, and showOnPlaybackEnded is false, hide the grid on playback ended
Fixes FEC-11884
> fix(FEC-11884): Related - System allows to choose any video from the grid when showOnPlaybackDone = false

- src/components/related-overlay/related-overlay.scss
- src/components/related-overlay/related-overlay.tsx
When the overlay is hidden, reset the grid state by returning an empty div instead of returning the grid component
> fix(FEC-12048): Related - System saves the grid's page after scrolling using pagination

- src/components/entry/grid-entry.tsx
- src/components/entry/minimal-grid-entry.tsx
- src/components/related-grid/grid-utils.tsx
- src/components/related-grid/related-grid.tsx
Fix entry data slice and add key to grid entries which was removed during responsiveness refactor
Resolves FEC-12106
> fix(FEC-12106): Related Grid shows wrong data after page 2

- src/components/related-overlay/related-overlay.tsx
Prevent showing the overlay when size breakpoint is tiny and video is paused
Resolves FEC-12119
> fix(FEC-12119): Related grid responsiveness: Possible to stop player's navigation when width<=279

- src/components/entry/entry.scss
- src/components/pre-playback-play-overlay-wrapper/pre-playback-play-overlay-wrapper.scss
- src/components/related-grid/related-grid.scss
- src/components/related-overlay/related-overlay.scss
Add missing vendor prefixes to css, including -webkit-backdrop-filter
Resolves FEC-12148
> fix(FEC-12148): Related Grid - Grid background in Safari has no blur effect

- src/components/thumbnail/thumbnail.tsx
Add missing dependencies to useEffect which caused it to not be called if an image failed to load
Resolves FEC-12145
> fix(FEC-12145): Related Grid - Some images are broken

- src/components/next/next.scss
- src/components/next/next.tsx
- src/related.tsx
Update next button props following FEC-12154 fix in playkit-ui and pass showPreview prop
Resolves FEC-12149
> fix(FEC-12149): Related Grid - Next button position is wrong in live entries

- src/components/entry/base-next-entry.tsx
When timeout was moved out of countdown component (because now countdown isn't always shown), clear timeout wasn't copied
It was needed to clear the timeout and also add stop propagation to prevent play now click from activating onEntryClick by mistake
Resolves FEC-12138
> fix(FEC-12138): Related grid responsiveness: New video is started to play after clicking "Play Now" and waiting 1-10s for extSources

- src/components/pre-playback-play-overlay-wrapper/pre-playback-play-overlay-wrapper.scss
- src/components/pre-playback-play-overlay-wrapper/pre-playback-play-overlay-wrapper.tsx
Fix styles of start over and adjust to player ui style
Resolves FEC-12142
> fix(FEC-12142): Related grid responsiveness: Replay icon not displayed with full size after finishing the video -> Cancel

- src/components/entry/base-next-entry.tsx
- src/related-manager.ts
Refactor countdown timeout to allow clearing it when a grid entry is clicked
Resolves FEC-12184
> fix(FEC-12184): Related grid responsiveness: New video is started to play after choosing any video from finished and waiting 1-10s for Context

- src/components/entry/entry.scss
flex-basis (default width) is auto (identical to width) by default, but IE11 ignores that a value of auto for that property
so as a workaround we set flex-shrink to 0 to prevent next entry width from shrinking
Resolves FEC-12240
> fix(FEC-12240): Related Entries - Next entry width is wrong in IE11

- src/components/entry/base-next-entry.tsx
- src/components/entry/grid-entry.tsx
- src/components/entry/minimal-grid-entry.tsx
Entries were changed from buttons to anchor tags since having the screen reader describe them as "links" instead of "buttons" seems more intuitive. 
however anchor tags don't have a default keydown handler like buttons, so it has to be added explicitly
Resolves FEC-12234
> fix(FEC-12234): Related grid accessibility: Pressing of the "Enter" and "Space" keys don't open a chosen video after tabulation

- src/components/related-overlay/related-overlay.scss
removed flex style from overlay (that wasn't actually used because of absolute positioning) which caused IE11 to position the grid incorrectly
Resolves FEC-12241
> fix(FEC-12241): Related Entries - Grid is centered incorrectly in IE11

- src/components/entry/entry.scss
IE11 ignores some of the css styles used for buttons, so they had to be reworked with other styles instead
Resolves FEC-12242
> fix(FEC-12242): Related Entries - Play Now button in IE has incorrect style, dimensions and position

- src/components/entry-image/entry-image.tsx
- src/components/entry/entry.scss
- src/components/entry/list-entry-placeholder.tsx
- src/components/entry/list-entry.tsx
- src/components/multiline-text/multiline-text.scss
- src/components/multiline-text/multiline-text.tsx
- src/components/related-countdown-preview/related-countdown-preview.tsx
- src/components/thumbnail/thumbnail.scss
- src/components/thumbnail/thumbnail.tsx
- src/services/image-service.ts
Allow entry images to either have explicit dimensions or to adjust to the container height while keeping the 16:9 ratio.
Resolves FEC-12822
> fix(FEC-12822): Related videos in the kitchen sink panel on top or on the bottom should be responsive

- src/related.tsx
Fix for reopen - remove duplicate code which caused related preview panel to be added twice.
Resolves FEC-12869
> fix(FEC-12869): Related - Related plugin blocks "up next in" for playlist

- src/related-manager.ts
When the user selects an entry from the list/grid, the entry is cycled to the end of the array of related entries.
However, internalIndex - which is used as the unique identifier of the entry for render - wasn't updated during this reorder, and this caused the display to not be updated.
The solution is to update internalIndex on every reorder of the array.
> fix(FEC-12884): Related Plugin Playing wrong Videos

- src/components/related-overlay/related-overlay.scss
resolves: https://kaltura.atlassian.net/browse/FEC-12937
fix relative layout if dual-screen active
> fix(FEC-12937): when the related overlay is displayed the minimized video of the dual screen is on top of the overly and it should be below

- src/index.ts
- src/related.tsx
**fix: Wrong and inconsistent order of plugins**
**fix: Plugins buttons sometimes display with the wrong icon**
**solves: [FEC-13517](https://kaltura.atlassian.net/browse/FEC-13517) [FEC-13517](https://kaltura.atlassian.net/browse/FEC-13517)**
[FEC-13517]: https://kaltura.atlassian.net/browse/FEC-13517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FEC-13517]: https://kaltura.atlassian.net/browse/FEC-13517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://github.com/kaltura/playkit-js-ui-managers/pull/51
https://github.com/kaltura/playkit-js-transcript/pull/175
https://github.com/kaltura/playkit-js-share/pull/38
https://github.com/kaltura/playkit-js-moderation/pull/74 …
> fix(FEC-13517): Wrong and inconsistent order of plugins

- src/components/related-overlay/related-overlay.tsx
- src/event/related-event.d.ts
- src/event/related-event.js
- src/related-manager.ts
Add Events (used by kava analytics)
> fix(FEC-13725): [Related Plugin]: Add Events (used by kava analytics)

- src/components/pre-playback-play-overlay-wrapper/pre-playback-play-overlay-wrapper.tsx
Description of the Changes
Issue:
When multiple players are embedded in single page, the screen reader's element list does not identify which button related to which player.
Fix:
Adding the entry name to the aria-label of play, pause, start over buttons
Resolves [ADA-17](https://kaltura.atlassian.net/browse/ADA-17)
[ADA-17]: https://kaltura.atlassian.net/browse/ADA-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ADA-17): Playback button labels are generic and not video specific

- src/components/related-list/related-list.tsx
- src/related-manager.ts
- src/related.tsx
- Changed function 'set isListVisible' to function 'updateListVisibility'.
- Added a new boolean variable called 'userInteraction' with default value 'false'.
- The function 'updateListVisibility' gets 'userInteraction =  true' only in places where the user in fact
clicked the button to close the related list.
[FEC-14031](https://kaltura.atlassian.net/browse/FEC-14031)
[FEC-14031]: https://kaltura.atlassian.net/browse/FEC-14031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-14031): RELATED_CLOSE is being sent upon every entry change in playlist

- src/components/list-toggle-button/list-toggle-button.tsx
This solves https://kaltura.atlassian.net/browse/ADA-1736. 
I've added the missing tooltip.
It sets the Tooltip position to always be bottom-left.
Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.
> fix(ADA-1736) - Add tooltip and tooltip strict position
